version: '3.6'
services:
    builder_watch_css:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./process_sass.js:/srv/app/process_sass.js
            - ./watch_css.sh:/srv/app/build.sh
            - ./package.json:/srv/app/package.json
            - ..:/srv/app/ircam_www_theme
    builder_watch_js:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./watch_js.sh:/srv/app/build.sh
            - ./package.json:/srv/app/package.json
            - ..:/srv/app/ircam_www_theme
